# Copyright (c) 2023 Joseph Hale
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---  # Denotes the start of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395
name: GrandExchange
version: 1.0.0
main: cl.angel.ge.GrandExchangePlugin
api-version: 1.21
author: Nortarox
description: Sistema de mercado global tipo Grand Exchange


commands:
  ge:
    description: Abre el Grand Exchange
    usage: /ge


... # Denotes the end of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395